# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'capturePreview.ui'
#
# Created: Mon Apr 18 20:13:49 2011
#      by: PySide uic UI code generator
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_capturePreview(object):
    def setupUi(self, capturePreview):
        capturePreview.setObjectName("capturePreview")
        capturePreview.resize(1234, 505)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(capturePreview.sizePolicy().hasHeightForWidth())
        capturePreview.setSizePolicy(sizePolicy)
        self.gridLayout = QtGui.QGridLayout(capturePreview)
        self.gridLayout.setObjectName("gridLayout")
        self.previewGraphicsView = QtGui.QGraphicsView(capturePreview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.previewGraphicsView.sizePolicy().hasHeightForWidth())
        self.previewGraphicsView.setSizePolicy(sizePolicy)
        self.previewGraphicsView.setObjectName("previewGraphicsView")
        self.gridLayout.addWidget(self.previewGraphicsView, 0, 0, 5, 1)
        self.newCaptureButton = QtGui.QPushButton(capturePreview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newCaptureButton.sizePolicy().hasHeightForWidth())
        self.newCaptureButton.setSizePolicy(sizePolicy)
        self.newCaptureButton.setObjectName("newCaptureButton")
        self.gridLayout.addWidget(self.newCaptureButton, 0, 1, 1, 1)
        self.groupBox = QtGui.QGroupBox(capturePreview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.activateAllLightsButton = QtGui.QPushButton(self.groupBox)
        self.activateAllLightsButton.setCheckable(False)
        self.activateAllLightsButton.setChecked(False)
        self.activateAllLightsButton.setDefault(False)
        self.activateAllLightsButton.setFlat(False)
        self.activateAllLightsButton.setObjectName("activateAllLightsButton")
        self.gridLayout_2.addWidget(self.activateAllLightsButton, 1, 0, 1, 2)
        self.deactivateAllLightsButton = QtGui.QPushButton(self.groupBox)
        self.deactivateAllLightsButton.setObjectName("deactivateAllLightsButton")
        self.gridLayout_2.addWidget(self.deactivateAllLightsButton, 3, 0, 1, 2)
        self.activateSingleLightComboBox = QtGui.QComboBox(self.groupBox)
        self.activateSingleLightComboBox.setFrame(True)
        self.activateSingleLightComboBox.setObjectName("activateSingleLightComboBox")
        self.gridLayout_2.addWidget(self.activateSingleLightComboBox, 2, 1, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 2, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 1, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(capturePreview)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lockAutofocusButton = QtGui.QPushButton(self.groupBox_2)
        self.lockAutofocusButton.setObjectName("lockAutofocusButton")
        self.gridLayout_3.addWidget(self.lockAutofocusButton, 0, 0, 1, 1)
        self.unlockAutofocusButton = QtGui.QPushButton(self.groupBox_2)
        self.unlockAutofocusButton.setObjectName("unlockAutofocusButton")
        self.gridLayout_3.addWidget(self.unlockAutofocusButton, 1, 0, 1, 1)
        self.autofocusLockStatusLabel = QtGui.QLabel(self.groupBox_2)
        self.autofocusLockStatusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.autofocusLockStatusLabel.setObjectName("autofocusLockStatusLabel")
        self.gridLayout_3.addWidget(self.autofocusLockStatusLabel, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 1, 1, 1, 1)

        self.retranslateUi(capturePreview)
        QtCore.QMetaObject.connectSlotsByName(capturePreview)

    def retranslateUi(self, capturePreview):
        capturePreview.setWindowTitle(QtGui.QApplication.translate("capturePreview", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.newCaptureButton.setText(QtGui.QApplication.translate("capturePreview", "Capture Image", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("capturePreview", "Lighting", None, QtGui.QApplication.UnicodeUTF8))
        self.activateAllLightsButton.setText(QtGui.QApplication.translate("capturePreview", "Activate All Lights", None, QtGui.QApplication.UnicodeUTF8))
        self.deactivateAllLightsButton.setText(QtGui.QApplication.translate("capturePreview", "Deactivate All Lights", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("capturePreview", "Activate Light #", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("capturePreview", "Camera", None, QtGui.QApplication.UnicodeUTF8))
        self.lockAutofocusButton.setText(QtGui.QApplication.translate("capturePreview", "Autofocus and Lock", None, QtGui.QApplication.UnicodeUTF8))
        self.unlockAutofocusButton.setText(QtGui.QApplication.translate("capturePreview", "Unlock Focus", None, QtGui.QApplication.UnicodeUTF8))
        self.autofocusLockStatusLabel.setText(QtGui.QApplication.translate("capturePreview", "---", None, QtGui.QApplication.UnicodeUTF8))

